### PR TITLE
Edward gonzalez branch

### PR DESCRIPTION
**Pull request by eddygonzalez9708**
# Description

The following changes were made to the home page: 

1. A footer section was added. 
2. Modals were created for the create quiz, login, and sign up buttons. 
3. Color Scheme changed was changed to a type of blue. 
4. Class names for CSS styles to follow clear naming conventions. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Used Chrome to display the landing page. All HTML code and CSS styles display as expected. 

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My code has been reviewed by at least one peer
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bbenefield89** [comment]
Looks great, thanks for fixing those warnings.

**Comment by eddygonzalez9708** [comment]
No problem!

**Comment by bdurb** [comment]
Naming conventions look good.  Warnings resolved.  Merging pull request.

**Comment by bdurb** [comment]
Closed in error.  Merging pull request.

**Pull request merged**
